# Dockerfile.python
FROM ubuntu:latest

# Aktualizacja repozytoriów i instalacja Pythona 3.10 oraz pip
RUN apt-get update && \
    apt-get install -y python3.10 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Sprawdzenie wersji Pythona przy starcie kontenera
CMD ["python3.10", "--version"]
